version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: news_api_laravel
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    depends_on:
      - db
    networks:
      - laravel_network
  
  web:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel_network

  db:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: news_api
      MYSQL_USER: news_api
      MYSQL_PASSWORD: news_api
      MYSQL_ROOT_PASSWORD: root9494
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel_network


volumes:
  db_data:

networks:
  laravel_network: