<?php

/** 
 * This section contains array to map the news categories provided by source into Project Default cateory names
 * Each News sources should register the news type.
 * If no mapping found, the news entry will be saved as 'default'
 */

return [
    'categories' => [
        'default' => 'news',
        'source_preset' => [
            'sport' => 'sports',
            'australia-news' => 'news',
            'news' => 'news',
            'world' => 'news',
            'arts' => 'arts',
            'tv-and-radio' => 'media',
            'artanddesign' => 'arts',
            'lifestyle_culture' => 'lifestyle_culture',
            'culture' => 'lifestyle_culture',
            'community' => 'lifestyle_culture',
            'fashion' => 'fashion',
            'commentisfree' => 'opinions_views',
            'opinion' => 'opinions_views',
            'animals-farmed' => 'farming_pets',
            'food' => 'food',
            'health' => 'health_fitness',
            'environment' => 'environment',
            'better-business' => 'bussiness_economy',
            'business' => 'bussiness_economy',
            'uk/business' => 'bussiness_economy',
            'us/business' => 'bussiness_economy',
            'au/business' => 'bussiness_economy',
            'business-to-business' => 'bussiness_economy',
            'books' => 'reading_education',
            'cardiff' => 'news',
            'childrens-books-site' => 'reading_education',
            'science' => 'reading_education',
            'cities' => 'travel_places',
            'travel/offers' => 'travel_places',
            'au/culture' => 'lifestyle_culture',
            'us/culture' => 'lifestyle_culture',
            'uk/culture' => 'lifestyle_culture',
            'culture-network' => 'lifestyle_culture',
            'culture-professionals-network' => 'lifestyle_culture',
            'edinburgh' => 'news',
            'wellness' => 'health_fitness',
            'au/wellness' => 'health_fitness',
            'us/wellness' => 'health_fitness',
            'uk/wellness' => 'health_fitness',
            'weather' => 'weather',
            'us' => 'news',
            'climate' => 'weather',
            'realestate' => 'bussiness_economy',
            'realestate' => 'bussiness_economy',
            't-magazine' => 't-magazine',
        ],
        'preset' => [
            'sports' => 'Sports',
            'news' => 'News & Stories',
            'arts' => 'Arts and Designs',
            'media' => 'TV,Radio,Movies',
            'arts' => 'Arts and Designs',
            'lifestyle_culture' => 'Life Style And Culture',
            'fashion' => 'Fashion',
            'shopping' => 'Shopping',
            'opinions_views' => 'Opinions And Views',
            'farming_pets' => 'Farming And Pets',
            'food' => 'Food',
            'health_fitness' => 'Health and Fitness',
            'environment' => 'Environment',
            'bussiness_economy' => 'Bussiness And Economy',
            'reading_education' => 'Reading And Education',
            'travel_places' => 'Travel And Places',
            'weather' => 'Weather',
            't-magazine' => 'T Magazine',
        ],
    ],
    'sources' => [
        'the_guardian' => 'The Guardian',
        'ny_times' => 'The New York Times',
        'open_news' => 'Open News',
    ],
];